### PR TITLE
Added instant profile look up

### PR DESCRIPTION
**Pull request by marcusshepp**
And did some other stuff as I looked around

clear icon on search

added notifications on success search and failed search
they can be swiped down to dismiss them

made searching disabled when there is no text in the search bar

### CODE REVIEW

**Comment by Vasilion** [comment]
gangster shit, only thing id say is swap the colors to use the theme colors for the notifications and then obviously that bug we texted about.

**Comment by Vasilion** [comment]
gunna have some conflicts now, if u ever get back to doing this, added quite a bit more data into the results feed.

**Comment by marcusshepp** [comment]
This is tested and ready to merge

**Comment by marcusshepp** [comment]
I also think you might have your linter off, your project settings are set to extend angular-eslint recommended, but you're committing double equals and empty lifecycle hooks etc. So, I'm assuming your vscode typescript linting settings are off.

image

image

**Review by Vasilion — APPROVED** [review]

**Pull request merged**
